# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QSWOT
                                 A QGIS plugin
 Plugin for loading SWOT data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-22
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Nima Asadi
        email                : nima.asadi.edu@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QDateTime, QDate
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QSpinBox, QMessageBox
from qgis.core import (
    QgsProject, QgsVectorLayer, QgsField, QgsFeature, QgsGeometry,
    QgsJsonUtils, QgsMessageLog, Qgis, QgsApplication, QgsTask,
    QgsLineSymbol, QgsFillSymbol, QgsMarkerSymbol, QgsSingleSymbolRenderer,
)
from .resources import *
from .src.swot_dialog import QSWOTDialog
from .src.api import HydrocronReachTask, HydrocronLakeTask
from .src.swot_fields import field_type, coerce_value
from .src.statistics_dialog import StatisticsDialog
from functools import partial
from typing import Any, Optional, List
from datetime import date

import os.path
import json


class QSWOT:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'QSWOT_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&QSWOT')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.river_task = None
        self.lake_task = None
        self.river_layer = None
        # Lakes: poly + point because Hydrocron returns both, and a memory
        # layer can only hold one geometry type. Lazily added to the project.
        self.lake_poly_layer = None
        self.lake_point_layer = None
        self._lake_poly_added = False
        self._lake_point_added = False
        self._river_zoomed = False
        self._lake_zoomed = False


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('QSWOT', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToWebMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar assets inside the QGIS GUI."""

        icon_path = ':/plugins/swot/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'QSWOT'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginWebMenu(
                self.tr(u'&QSWOT'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        if self.first_start:
            self.first_start = False
            self.dlg = QSWOTDialog()
            # Connect signals once — calling run() repeatedly would otherwise
            # stack duplicate connections and each click would fire N times.
            self.dlg.river_fetch_all.toggled.connect(
                partial(self.on_fetch_all_changed, 'river')
            )
            self.dlg.lake_fetch_all.toggled.connect(
                partial(self.on_fetch_all_changed, 'lake')
            )
            self.dlg.river_statistics_btn.clicked.connect(self.open_river_statistics)
            self.dlg.river_lake_btn.clicked.connect(self.open_lake_statistics)

        self.set_defaults()

        feature_types = 0
        river = 2
        lake = 4

        # exec_() alone handles showing the dialog modally. A preceding show()
        # would render it non-modally first, causing the close button to
        # require two or three clicks to actually dismiss the dialog.
        if self.dlg.exec_():
            river_name = self.dlg.river_name.text()
            lake_name = self.dlg.lake_name.text()

            if all([river_name, lake_name]):
                from .src.swot_dataset_dialog import QSWOTDatasetDialog
                dset_dlg = QSWOTDatasetDialog()
                dset_dlg.river_name.setText(f'{river_name} River')
                dset_dlg.lake_name.setText(f'{lake_name} Lake')
                if dset_dlg.exec_():
                    if dset_dlg.river_name.isChecked():
                        feature_types |= river
                    if dset_dlg.lake_name.isChecked():
                        feature_types |= lake
            elif river_name:
                feature_types |= river
            elif lake_name:
                feature_types |= lake
            else:
                self.iface.messageBar().pushMessage(
                    "Missing Input",
                    "River/Lake name is required.",
                    level=Qgis.Warning,
                    duration=5
                )
                return

            if feature_types == river:
                self.process_river()
            elif feature_types == lake:
                self.process_lake()
            elif feature_types == river | lake:
                self.process_river()
                self.process_lake()

    def set_defaults(self):
        current_time = QDateTime.currentDateTime()
        self.dlg.river_ts_start.setDateTime(current_time)
        self.dlg.river_ts_end.setDateTime(current_time)
        self.dlg.lake_ts_start.setDateTime(current_time)
        self.dlg.lake_ts_end.setDateTime(current_time)
        self.dlg.river_name.setText('')
        self.dlg.lake_name.setText('')

    def on_fetch_all_changed(self, feature_type: str, checked: bool):
        if feature_type == 'river':
            self.dlg.river_fetch_manual.setEnabled(not checked)
        elif feature_type == 'lake':
            self.dlg.lake_fetch_manual.setEnabled(not checked)

    def serialize(self, prefix: str):
        if prefix not in ['river', 'lake']:
            return
        get = lambda attr: getattr(self.dlg, f'{prefix}_{attr}')

        fields = self.dlg.selected_fields(prefix)
        limit = -1 if get('fetch_all').isChecked() else get('fetch_manual').value()
        start_time_wdg = get('ts_start')
        end_time_wdg = get('ts_end')

        name_key = 'river_name' if prefix == 'river' else 'lake_name'
        ids_key = 'reach_ids' if prefix == 'river' else 'lake_ids'

        return {
            name_key: get('name').text(),
            ids_key: [],
            'start_time': start_time_wdg.dateTime().toString("yyyy-MM-ddTHH:mm:ss'Z'"),
            'end_time': end_time_wdg.dateTime().toString("yyyy-MM-ddTHH:mm:ss'Z'"),
            'fields': fields,
            'start_time_ordinal': self.to_ordinal(start_time_wdg.date()),
            'end_time_ordinal': self.to_ordinal(end_time_wdg.date()),
            'limit': limit,
        }

    def process_river(self):
        if not (data := self.serialize('river')):
            return

        if not self.confirm_replace_task('river_task', "river download"):
            return

        self.river_layer = self.build_river_layer(data['fields'])
        self._river_zoomed = False
        QgsProject.instance().addMapLayer(self.river_layer)

        self.river_task = HydrocronReachTask(
            description="Downloading Hydrocron Reaches",
            **data,
            callback=self.on_river_download_finished,
        )
        self.river_task.features_ready.connect(self.append_river_features)
        QgsApplication.taskManager().addTask(self.river_task)

    def process_lake(self):
        if not (data := self.serialize('lake')):
            return

        if not self.confirm_replace_task('lake_task', "lake download"):
            return

        self.lake_poly_layer = self.build_lake_poly_layer(data['fields'])
        self.lake_point_layer = self.build_lake_point_layer(data['fields'])
        self._lake_poly_added = False
        self._lake_point_added = False
        self._lake_zoomed = False

        self.lake_task = HydrocronLakeTask(
            description="Downloading Hydrocron Lakes",
            **data,
            callback=self.on_lake_download_finished,
        )
        self.lake_task.features_ready.connect(self.append_lake_features)
        QgsApplication.taskManager().addTask(self.lake_task)

    def confirm_replace_task(self, attr_name, label):
        existing = getattr(self, attr_name)
        if not existing:
            return True
        if existing.status() not in [QgsTask.Queued, QgsTask.Running]:
            return True
        reply = QMessageBox.question(
            self.dlg,
            "Task in Progress",
            f"A {label} is already running. Would you like to stop it and start a new search?",
            QMessageBox.Yes | QMessageBox.No,
            QMessageBox.No,
        )
        if reply != QMessageBox.Yes:
            return False
        existing.cancel()
        setattr(self, attr_name, None)
        return True

    def build_river_layer(self, fields):
        uri = "LineString?crs=EPSG:4326&index=yes"
        layer = QgsVectorLayer(uri, "Hydrocron Reaches", "memory")
        self.add_fields(layer, fields)
        symbol = QgsLineSymbol.createSimple({'color': 'red', 'line_width': '0.6'})
        layer.setRenderer(QgsSingleSymbolRenderer(symbol))
        return layer

    def build_lake_poly_layer(self, fields):
        layer = QgsVectorLayer(
            "MultiPolygon?crs=EPSG:4326&index=yes", "Hydrocron Lakes", "memory"
        )
        self.add_fields(layer, fields)
        symbol = QgsFillSymbol.createSimple({
            'color': '80,150,255,120',          # translucent blue fill
            'outline_color': '20,80,180',
            'outline_width': '0.4',
        })
        layer.setRenderer(QgsSingleSymbolRenderer(symbol))
        return layer

    def build_lake_point_layer(self, fields):
        layer = QgsVectorLayer(
            "Point?crs=EPSG:4326&index=yes", "Hydrocron Lakes (Points)", "memory"
        )
        self.add_fields(layer, fields)
        symbol = QgsMarkerSymbol.createSimple({
            'name': 'circle',
            'color': '20,80,180',
            'size': '2.5',
        })
        layer.setRenderer(QgsSingleSymbolRenderer(symbol))
        return layer

    @staticmethod
    def add_fields(layer, fields):
        provider = layer.dataProvider()
        provider.addAttributes([
            QgsField(name, field_type(name))
            for name in sorted(fields)
        ])
        layer.updateFields()

    def append_river_features(self, features):
        qgs = self.convert_features(self.river_layer, features)
        self.flush_to_layer(self.river_layer, qgs, zoom_attr='_river_zoomed')

    def append_lake_features(self, features):
        poly_qgs = self.convert_features(self.lake_poly_layer, features, accept=('Polygon', 'MultiPolygon'))
        point_qgs = self.convert_features(self.lake_point_layer, features, accept=('Point',))

        # Lazy add to project so empty layers don't clutter the legend.
        if poly_qgs and not self._lake_poly_added:
            QgsProject.instance().addMapLayer(self.lake_poly_layer)
            self._lake_poly_added = True
        if point_qgs and not self._lake_point_added:
            QgsProject.instance().addMapLayer(self.lake_point_layer)
            self._lake_point_added = True

        self.flush_to_layer(self.lake_poly_layer, poly_qgs, zoom_attr='_lake_zoomed')
        self.flush_to_layer(self.lake_point_layer, point_qgs, zoom_attr='_lake_zoomed')

    def convert_features(self, layer, items, accept=None):
        """Parse GeoJSON items into QgsFeatures for `layer`, optionally
        filtering by GeoJSON geometry type."""
        if layer is None:
            return []
        field_names = {f.name() for f in layer.fields()}
        out = []
        for item in items:
            geom_json = item.get('geometry')
            if not geom_json:
                continue
            if accept is not None and geom_json.get('type') not in accept:
                continue
            geom = QgsJsonUtils.geometryFromGeoJson(json.dumps(geom_json))
            if geom.isNull():
                QgsMessageLog.logMessage(
                    f"Skipping feature with unparseable GeoJSON geometry: {geom_json!r}",
                    level=Qgis.Warning,
                )
                continue
            feat = QgsFeature(layer.fields())
            feat.setGeometry(geom)
            for name, value in (item.get('properties') or {}).items():
                if name in field_names:
                    feat.setAttribute(name, coerce_value(name, value))
            out.append(feat)
        return out

    def flush_to_layer(self, layer, qgs_features, zoom_attr):
        if not qgs_features or layer is None:
            return
        if not QgsProject.instance().mapLayer(layer.id()):
            return
        layer.dataProvider().addFeatures(qgs_features)
        layer.updateExtents()
        layer.triggerRepaint()
        if not getattr(self, zoom_attr):
            setattr(self, zoom_attr, True)
            self.zoom_to_layer(layer)

    def on_river_download_finished(self, features_data: Any):
        self.river_task = None
        self.activate_if_present(self.river_layer)

    def on_lake_download_finished(self, features_data: Any):
        self.lake_task = None
        # Prefer activating the polygon layer; fall back to points if that's
        # the only one with data.
        if self._lake_poly_added:
            self.activate_if_present(self.lake_poly_layer)
        elif self._lake_point_added:
            self.activate_if_present(self.lake_point_layer)

    def activate_if_present(self, layer):
        if layer is None or not QgsProject.instance().mapLayer(layer.id()):
            return
        self.iface.setActiveLayer(layer)

    # ---- statistics dialogs --------------------------------------------

    def open_river_statistics(self):
        self.open_statistics_dialog(self.river_layer, "river")

    def open_lake_statistics(self):
        # Lake layers are added lazily — only after their first matching
        # feature batch arrives. Pick whichever actually made it into the
        # project (prefer polygons, fall back to points).
        if self._lake_poly_added:
            layer = self.lake_poly_layer
        elif self._lake_point_added:
            layer = self.lake_point_layer
        else:
            layer = None

        # A lake search like "caspian" returns features for many physically
        # separate lakes — computing stats across all of them mixed together
        # is misleading. Require the user to pick the lake of interest first.
        if layer is not None and QgsProject.instance().mapLayer(layer.id()):
            if layer.selectedFeatureCount() == 0:
                QMessageBox.information(
                    self.dlg,
                    "Select a lake first",
                    "Lake fetches can return features for many separate lakes "
                    "matching the search (e.g. 'caspian' returns Caspian Sea "
                    f"<i>and</i> Caspian Lake). Open the <b>{layer.name()}</b> "
                    "layer's attribute table, select the rows for the lake "
                    "you want to analyze, then click <b>Lake Statistic</b> "
                    "again.",
                )
                return

        self.open_statistics_dialog(layer, "lake", default_subset='selected')

    def open_statistics_dialog(self, layer, label, default_subset='all'):
        if layer is None or not QgsProject.instance().mapLayer(layer.id()):
            QMessageBox.information(
                self.dlg,
                "No data",
                f"No {label} layer is loaded yet. "
                f"Run a {label} fetch first, then open the statistics dialog.",
            )
            return
        StatisticsDialog(layer, parent=self.dlg,
                         default_subset=default_subset).exec_()

    def zoom_to_layer(self, layer):
        layer.updateExtents()
        extent = layer.extent()
        if extent.isEmpty():
            return
        extent.scale(30)
        canvas = self.iface.mapCanvas()
        canvas.setExtent(extent)
        canvas.refresh()
        self.iface.setActiveLayer(layer)

    @staticmethod
    def to_ordinal(q_date: QDate):
        py_date = date(q_date.year(), q_date.month(), q_date.day())
        return py_date.toordinal()
