# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QSWOTDialog
                                 A QGIS plugin
 Plugin for loading SWOT data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-22
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Nima Asadi
        email                : nima.asadi.edu@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from typing import Any, Tuple

from .swot_fields import RIVER_FIELDS, LAKE_FIELDS

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'swot_dialog_base.ui'))


class QSWOTDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(QSWOTDialog, self).__init__(parent)
        self.setupUi(self)

        self.field_checkboxes = {'river': {}, 'lake': {}}
        self._populate_field_tabs('river', self.river_query_fields_tabs, RIVER_FIELDS)
        self._populate_field_tabs('lake', self.lake_query_fields_tabs, LAKE_FIELDS)

    def _populate_field_tabs(self, prefix: str, tab_widget: Any, spec: Tuple):
        registry = self.field_checkboxes[prefix]
        for tab_title, fields in spec:
            page = QtWidgets.QWidget()
            scroll = QtWidgets.QScrollArea(page)
            scroll.setWidgetResizable(True)
            scroll.setFrameShape(QtWidgets.QFrame.NoFrame)

            inner = QtWidgets.QWidget()
            inner_layout = QtWidgets.QVBoxLayout(inner)
            inner_layout.setContentsMargins(4, 4, 4, 4)
            inner_layout.setSpacing(4)

            current_group = object()  # sentinel != None and != any string
            current_layout = inner_layout
            for key, label, checked, group in fields:
                if group != current_group:
                    current_group = group
                    if group is None:
                        current_layout = inner_layout
                    else:
                        box = QtWidgets.QGroupBox(group, inner)
                        current_layout = QtWidgets.QVBoxLayout(box)
                        current_layout.setContentsMargins(8, 4, 8, 4)
                        current_layout.setSpacing(2)
                        inner_layout.addWidget(box)

                cb = QtWidgets.QCheckBox(label)
                cb.setChecked(checked)
                current_layout.addWidget(cb)
                registry[key] = cb

            inner_layout.addStretch(1)
            scroll.setWidget(inner)

            page_layout = QtWidgets.QVBoxLayout(page)
            page_layout.setContentsMargins(0, 0, 0, 0)
            page_layout.addWidget(scroll)
            tab_widget.addTab(page, tab_title)

    def selected_fields(self, prefix):
        return {k for k, cb in self.field_checkboxes[prefix].items() if cb.isChecked()}
