RIVER_FIELDS = [
    ("Time & Orbit", [
        ("time", "Time (UTC)", True, None),
        ("time_tai", "Time (TAI)", True, None),
        ("time_str", "Time (String)", True, None),
        ("cycle_id", "Cycle ID", False, None),
        ("pass_id", "Pass ID", False, None),
        ("range_start_time", "Start Time", False, None),
        ("range_end_time", "End Time", False, None),
        ("ingest_time", "Ingest Time", False, None),
    ]),
    ("Hydrology & Measurements", [
        ("wse", "WSE", True, "Water Surface Elevation (WSE)"),
        ("wse_u", "WSE Uncert.", True, "Water Surface Elevation (WSE)"),
        ("wse_r_u", "WSE Rand. Uncert.", False, "Water Surface Elevation (WSE)"),
        ("wse_c", "WSE Constr.", False, "Water Surface Elevation (WSE)"),
        ("wse_c_u", "WSE Constr. Uncert.", False, "Water Surface Elevation (WSE)"),
        ("slope", "Slope", True, "River Slope"),
        ("slope_u", "Slope Uncert.", True, "River Slope"),
        ("slope_r_u", "Slope Rand. Uncert.", False, "River Slope"),
        ("slope2", "Slope (Alt)", False, "River Slope"),
        ("slope2_u", "Slope (Alt) Uncert.", False, "River Slope"),
        ("slope2_r_u", "Slope (Alt) Rand. Uncert.", False, "River Slope"),
        ("width", "Width", True, "River Width"),
        ("width_u", "Width Uncert.", True, "River Width"),
        ("width_c", "Width Constr.", False, "River Width"),
        ("width_c_u", "Width Constr. Uncert.", False, "River Width"),
        ("area_total", "Total Area", True, "River Area"),
        ("area_tot_u", "Total Area Uncert.", True, "River Area"),
        ("area_detct", "Detected Area", False, "River Area"),
        ("area_det_u", "Detected Area Uncert.", False, "River Area"),
        ("area_wse", "Area used for WSE", False, "River Area"),
        ("d_x_area", "Area Change", False, "River Area"),
        ("d_x_area_u", "Area Change Uncert.", False, "River Area"),
    ]),
    ("Geometry & Topology", [
        ("geometry", "Geometry Shape", False, None),
        ("p_lat", "Latitude (Prior)", False, None),
        ("p_lon", "Longitude (Prior)", False, None),
        ("node_dist", "Node Distance", False, None),
        ("loc_offset", "Location Offset", False, None),
        ("xtrk_dist", "Cross-Track Dist.", False, None),
        ("geoid_hght", "Geoid Height", False, None),
        ("geoid_slop", "Geoid Slope", False, None),
        ("n_reach_up", "Upstream Reach Count", False, None),
        ("n_reach_dn", "Downstream Reach Count", False, None),
        ("rch_id_up", "Upstream IDs", False, None),
        ("rch_id_dn", "Downstream IDs", False, None),
        ("p_n_nodes", "Prior Node Count", False, None),
        ("p_dist_out", "Dist. to Outlet", False, None),
        ("p_length", "Prior Length", False, None),
        ("p_n_ch_max", "Max River Channels", False, None),
        ("p_n_ch_mod", "Mode River Channels", False, None),
    ]),
    ("River Discharge", [
        ("dschg_c", "Consens. Flow", False, "Consensus Model"),
        ("dschg_c_u", "Consens. Flow Uncert.", False, "Consensus Model"),
        ("dschg_csf", "Consens. Flow Frac.", False, "Consensus Model"),
        ("dschg_c_q", "Consens. Flow Qual.", False, "Consensus Model"),
        ("dschg_gc", "Gage Consens. Flow", False, "Consensus Model"),
        ("dschg_gc_u", "Gage Consens. Uncert.", False, "Consensus Model"),
        ("dschg_gcsf", "Gage Consens. Frac.", False, "Consensus Model"),
        ("dschg_gc_q", "Gage Consens. Qual.", False, "Consensus Model"),
        ("dschg_m", "MetroMan Flow", False, "MetroMan Model"),
        ("dschg_m_u", "MetroMan Uncert.", False, "MetroMan Model"),
        ("dschg_msf", "MetroMan Frac.", False, "MetroMan Model"),
        ("dschg_m_q", "MetroMan Qual.", False, "MetroMan Model"),
        ("dschg_gm", "Gage MetroMan Flow", False, "MetroMan Model"),
        ("dschg_gm_u", "Gage MetroMan Uncert.", False, "MetroMan Model"),
        ("dschg_gmsf", "Gage MetroMan Frac.", False, "MetroMan Model"),
        ("dschg_gm_q", "Gage MetroMan Qual.", False, "MetroMan Model"),
        ("dschg_b", "BAM Flow", False, "BAM Model"),
        ("dschg_b_u", "BAM Uncert.", False, "BAM Model"),
        ("dschg_bsf", "BAM Frac.", False, "BAM Model"),
        ("dschg_b_q", "BAM Qual.", False, "BAM Model"),
        ("dschg_gb", "Gage BAM Flow", False, "BAM Model"),
        ("dschg_gb_u", "Gage BAM Uncert.", False, "BAM Model"),
        ("dschg_gbsf", "Gage BAM Frac.", False, "BAM Model"),
        ("dschg_gb_q", "Gage BAM Qual.", False, "BAM Model"),
        ("dschg_h", "HiVDI Flow", False, "HiVDI Model"),
        ("dschg_h_u", "HiVDI Uncert.", False, "HiVDI Model"),
        ("dschg_hsf", "HiVDI Frac.", False, "HiVDI Model"),
        ("dschg_h_q", "HiVDI Qual.", False, "HiVDI Model"),
        ("dschg_gh", "Gage HiVDI Flow", False, "HiVDI Model"),
        ("dschg_gh_u", "Gage HiVDI Uncert.", False, "HiVDI Model"),
        ("dschg_ghsf", "Gage HiVDI Frac.", False, "HiVDI Model"),
        ("dschg_gh_q", "Gage HiVDI Qual.", False, "HiVDI Model"),
        ("dschg_o", "MOMMA Flow", False, "MOMMA Model"),
        ("dschg_o_u", "MOMMA Uncert.", False, "MOMMA Model"),
        ("dschg_osf", "MOMMA Frac.", False, "MOMMA Model"),
        ("dschg_o_q", "MOMMA Qual.", False, "MOMMA Model"),
        ("dschg_go", "Gage MOMMA Flow", False, "MOMMA Model"),
        ("dschg_go_u", "Gage MOMMA Uncert.", False, "MOMMA Model"),
        ("dschg_gosf", "Gage MOMMA Frac.", False, "MOMMA Model"),
        ("dschg_go_q", "Gage MOMMA Qual.", False, "MOMMA Model"),
        ("dschg_s", "SADS Flow", False, "SADS Model"),
        ("dschg_s_u", "SADS Uncert.", False, "SADS Model"),
        ("dschg_ssf", "SADS Frac.", False, "SADS Model"),
        ("dschg_s_q", "SADS Qual.", False, "SADS Model"),
        ("dschg_gs", "Gage SADS Flow", False, "SADS Model"),
        ("dschg_gs_u", "Gage SADS Uncert.", False, "SADS Model"),
        ("dschg_gssf", "Gage SADS Frac.", False, "SADS Model"),
        ("dschg_gs_q", "Gage SADS Qual.", False, "SADS Model"),
        ("dschg_i", "SIC4DVar Flow", False, "SIC4DVar Model"),
        ("dschg_i_u", "SIC4DVar Uncert.", False, "SIC4DVar Model"),
        ("dschg_isf", "SIC4DVar Frac.", False, "SIC4DVar Model"),
        ("dschg_i_q", "SIC4DVar Qual.", False, "SIC4DVar Model"),
        ("dschg_gi", "Gage SIC4DVar Flow", False, "SIC4DVar Model"),
        ("dschg_gi_u", "Gage SIC4DVar Uncert.", False, "SIC4DVar Model"),
        ("dschg_gisf", "Gage SIC4DVar Frac.", False, "SIC4DVar Model"),
        ("dschg_gi_q", "Gage SIC4DVar Qual.", False, "SIC4DVar Model"),
        ("dschg_q_b", "Flow Qual. Bitflag", False, "Flow Quality & Prior"),
        ("dschg_gq_b", "Gage Flow Qual. Bitflag", False, "Flow Quality & Prior"),
        ("p_maf", "Mean Annual Flow", False, "Flow Quality & Prior"),
    ]),
    ("Radar Metrics & Corrections", [
        ("layovr_val", "Radar Layover Value", False, None),
        ("dark_frac", "Dark Water Frac.", False, None),
        ("ice_clim_f", "Clim. Ice Flag", False, None),
        ("ice_dyn_f", "Dynamic Ice Flag", False, None),
        ("partial_f", "Partial Obs. Flag", False, None),
        ("n_good_nod", "Good Node Count", False, None),
        ("obs_frac_n", "Observed Node Frac.", False, None),
        ("xovr_cal_q", "Crossover Correct. Qual.", False, None),
        ("solid_tide", "Solid Earth Tide", False, None),
        ("load_tidef", "Load Tide F", False, None),
        ("load_tideg", "Load Tide G", False, None),
        ("pole_tide", "Pole Tide", False, None),
        ("dry_trop_c", "Dry Tropo. Correct.", True, None),
        ("wet_trop_c", "Wet Tropo. Correct.", True, None),
        ("iono_c", "Ionosphere Correct.", True, None),
        ("xovr_cal_c", "Crossover Correct.", False, None),
    ]),
    ("Reach Metadata & SWORD Prior", [
        ("reach_id", "Reach ID", True, None),
        ("river_name", "River Name", True, None),
        ("reach_q", "Reach Quality", False, None),
        ("reach_q_b", "Reach Qual. Bitflag", False, None),
        ("p_wse", "Prior WSE", False, None),
        ("p_wse_var", "Prior WSE Variance", False, None),
        ("p_width", "Prior Width", False, None),
        ("p_wid_var", "Prior Width Variance", False, None),
        ("p_dam_id", "Dam ID", False, None),
        ("p_low_slp", "Low Slope Flag", False, None),
        ("continent_id", "Continent ID", False, None),
        ("crid", "CRID", False, None),
        ("sword_version", "SWORD Version", False, None),
        ("collection_shortname", "Collection Name", False, None),
        ("collection_version", "Collection Version", False, None),
        ("granuleUR", "Granule UR", False, None),
    ]),
]

LAKE_FIELDS = [
    ("Time & Orbit", [
        ("time", "Time (UTC)", True, None),
        ("time_tai", "Time (TAI)", True, None),
        ("time_str", "Time (String)", True, None),
        ("cycle_id", "Cycle ID", False, None),
        ("pass_id", "Pass ID", False, None),
        ("range_start_time", "Start Time", False, None),
        ("range_end_time", "End Time", False, None),
        ("ingest_time", "Ingest Time", False, None),
    ]),
    ("Hydrology & Storage", [
        ("wse", "WSE", True, "Water Surface Elevation (WSE)"),
        ("wse_u", "WSE Uncert.", True, "Water Surface Elevation (WSE)"),
        ("wse_r_u", "WSE Rand. Uncert.", False, "Water Surface Elevation (WSE)"),
        ("wse_std", "WSE Std. Dev.", False, "Water Surface Elevation (WSE)"),
        ("area_total", "Total Area", True, "Lake Area"),
        ("area_tot_u", "Total Area Uncert.", True, "Lake Area"),
        ("area_detct", "Detected Area", False, "Lake Area"),
        ("area_det_u", "Detected Area Uncert.", False, "Lake Area"),
        ("ds1_l", "Storage Change 1", False, "Storage Change (ds)"),
        ("ds1_l_u", "Storage Change 1 Uncert.", False, "Storage Change (ds)"),
        ("ds1_q", "Storage Change 1 Qual.", False, "Storage Change (ds)"),
        ("ds1_q_u", "Storage Change 1 Qual. Uncert.", False, "Storage Change (ds)"),
        ("ds2_l", "Storage Change 2", False, "Storage Change (ds)"),
        ("ds2_l_u", "Storage Change 2 Uncert.", False, "Storage Change (ds)"),
        ("ds2_q", "Storage Change 2 Qual.", False, "Storage Change (ds)"),
        ("ds2_q_u", "Storage Change 2 Qual. Uncert.", False, "Storage Change (ds)"),
    ]),
    ("Geometry & Identifiers", [
        ("reach_id", "Reach ID", True, None),
        ("obs_id", "Observation ID", False, None),
        ("geometry", "Geometry Shape", False, None),
        ("p_lat", "Latitude (Prior)", False, None),
        ("p_lon", "Longitude (Prior)", False, None),
        ("xtrk_dist", "Cross-Track Dist.", False, None),
        ("overlap", "Overlap Fraction", False, None),
        ("n_overlap", "Number of Overlaps", False, None),
    ]),
    ("Radar Metrics & Corrections", [
        ("quality_f", "Quality Flag", True, None),
        ("qual_f_b", "Quality Flag Bitflag", False, None),
        ("layovr_val", "Radar Layover Value", False, None),
        ("dark_frac", "Dark Water Frac.", False, None),
        ("ice_clim_f", "Clim. Ice Flag", False, None),
        ("ice_dyn_f", "Dynamic Ice Flag", False, None),
        ("partial_f", "Partial Obs. Flag", False, None),
        ("xovr_cal_q", "Crossover Correct. Qual.", False, None),
        ("xovr_cal_c", "Crossover Correct.", False, None),
        ("geoid_hght", "Geoid Height", False, None),
        ("solid_tide", "Solid Earth Tide", False, None),
        ("load_tidef", "Load Tide F", False, None),
        ("load_tideg", "Load Tide G", False, None),
        ("pole_tide", "Pole Tide", True, None),
        ("dry_trop_c", "Dry Tropo. Correct.", True, None),
        ("wet_trop_c", "Wet Tropo. Correct.", True, None),
        ("iono_c", "Ionosphere Correct.", True, None),
    ]),
    ("Metadata & PLD Prior", [
        ("lake_name", "Lake Name", True, None),
        ("p_res_id", "Prior Res. ID", False, None),
        ("p_ref_wse", "Prior Ref. WSE", False, None),
        ("p_ref_area", "Prior Ref. Area", False, None),
        ("p_date_t0", "Prior Date T0", False, None),
        ("p_ds_t0", "Prior Storage Change T0", False, None),
        ("p_storage", "Prior Storage", False, None),
        ("continent_id", "Continent ID", False, None),
        ("crid", "CRID", False, None),
        ("PLD_version", "PLD Version", False, None),
        ("collection_shortname", "Collection Name", False, None),
        ("collection_version", "Collection Version", False, None),
        ("granuleUR", "Granule UR", False, None),
    ]),
]
